/* eslint-disable @typescript-eslint/require-await */

import Head from "next/head";
import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import { api } from "~/utils/api";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const { data: sessionData } = useSession()
  const router = useRouter()

  const groupCreate = api.group.create.useMutation()
  const groupDelete = api.group.delete.useMutation()
  const groupAddUser = api.group.addUsers.useMutation()
  const {data: userGroups} = api.user.getGroups.useQuery()

  function createGroup() {
    groupCreate.mutate(({name:'test group'}))
  }
  function deleteGroup(groupId: string) {
    groupDelete.mutate(({id: groupId}))
  }

  function invite (groupId: string) {
    groupAddUser.mutate({groupId, usersToAdd: [{email: 'sergio_5_00@hotmail.com'}]})
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex min-h-screen flex-col bg-gradient-to-b from-[#2e026d] to-[#15162c]">
          <div className="container text-white">
            

            {sessionData?.user && <button className="p-4 bg-red-600 rounded-md" onClick={createGroup}> New group </button>}

            <div>
              {userGroups?.map(group => <div className="flex gap-7" key={group.id}>
                  {group.name}  {group.id}
                  
                  <div onClick={()=> { deleteGroup(group.id)}}> DELETE </div>
                  <div onClick={()=> { invite(group.id)}}> INVITE DISCORD ACCOUNT </div>
                  <div onClick={() => { void router.push(`/invitation/${group.id}`)}}> SEE invitation </div>
              </div>)}
            </div>
            
            
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

