/* eslint-disable @typescript-eslint/require-await */

import Head from "next/head";
import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import { api } from "~/utils/api";
import { useRouter } from "next/router";
import { useRef } from "react";

const Home: NextPage = () => {
  const { data: sessionData } = useSession()
  const router = useRouter()

  const groupCreate = api.group.create.useMutation()
  const groupDelete = api.group.delete.useMutation()
  const {data: userGroups} = api.user.getGroups.useQuery()

  const newGroupNameRef = useRef<HTMLInputElement>(null)

  function createGroup() {
    groupCreate.mutate(({ name: newGroupNameRef.current?.value ?? 'New Group' }))
  }
  function deleteGroup(groupId: string) {
    groupDelete.mutate(({id: groupId}))
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="flex min-h-screen flex-col bg-gradient-to-b from-[#2e026d] to-[#15162c]">
          <div className="container text-white">
            
            <input className="text-black" type="text" ref={newGroupNameRef} />
            {sessionData?.user && <button className="p-4 bg-red-600 rounded-md" onClick={createGroup}> New group </button>}



            <div>
              {userGroups?.map(group => <div key={group.id} className="mb-5">
                  <p onClick={()=>void router.push(`/group/${group.id}`)} className="text-4xl font-bold cursor-pointer"> 
                    {group.name} 
                  </p>
              
                  <div className="flex gap-7">
                    {group.id}
                    
                    <div onClick={()=> { deleteGroup(group.id)}}> DELETE </div>
                    <div onClick={() => { void router.push(`/group/join/${group.id}`)}}> SEE invitation </div>
                  </div>
                  
              </div>)}
            </div>
            
            
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

